steps:
- name: gcr.io/cloud-builders/gcloud
  dir: 'client/'
  args:
  - kms
  - decrypt
  - --ciphertext-file=.env.enc
  - --plaintext-file=.env
  - --location=global
  - --keyring=firebase-api
  - --key=cloudbuild-env

- name: 'gcr.io/cloud-builders/npm'
  id: 'client-install'
  args: [ 'install' ]
  dir: 'client/'
  waitFor:
    - '-'

- name: 'gcr.io/cloud-builders/npm'
  id: 'client-build'
  args: [ 'run', 'build']
  dir: 'client/'
  waitFor:
    - 'client-install'

- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "client/client.yaml"]
  waitFor:
    - 'client-build'

- name: 'gcr.io/cloud-builders/npm'
  id: 'server-install'
  args: [ 'install' ]
  dir: 'server/'
  waitFor:
    - '-'

- name: 'gcr.io/cloud-builders/npm'
  id: 'server-build'
  args: [ 'run', 'build']
  dir: 'server/'
  waitFor:
    - 'server-install'

- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "server/api.yaml"]
  waitFor:
    - 'server-build'

timeout: "1600s"


