steps:
# - name: 'gcr.io/cloud-builders/npm'
#   args: [ 'install' ]
#   dir: 'client/'
- name: 'gcr.io/cloud-builders/npm'
  args: [ 'run', 'build']
  dir: 'client/'
# - name: 'gcr.io/cloud-builders/npm'
#   args: [ 'install' ]
#   dir: 'server/'
- name: 'gcr.io/cloud-builders/npm'
  args: [ 'run', 'build']
  dir: 'server/'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "client/client.yaml"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "server/api.yaml"]
timeout: "1600s"


